package dragon

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func out(libChan chan lib, w io.Writer) error {
	stdlib := map[string][]string{
		"unsafe": []string{
			"Alignof",
			"ArbitraryType",
			"Offsetof",
			"Pointer",
			"Sizeof",
		},
	}
	for lib := range libChan {
		objSlice, ok := stdlib[lib.path]
		if !ok {
			objSlice = []string{}
		}
		objSlice = append(objSlice, lib.object)
		stdlib[lib.path] = objSlice
	}

	_, err := fmt.Fprintf(w, `// AUTO-GENERATED BY dragon-imports

package imports

var stdlib = %#v
`, stdlib)

	return err
}

func outPath() string {
	for _, src := range srcDirs() {
		outPath := filepath.Join(src, "golang.org/x/tools/internal/imports")
		if _, err := os.Stat(outPath); err == nil {
			return outPath
		}
	}
	return ""
}
